spring:
  application:
    name: feedme

  datasource:
    url: jdbc:postgresql://localhost:5432/feedme
    username: feedme
    password: feedme
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false